export class DispatchController {
  constructor(bank){this.bank=bank;this.assignments=new Map();}
  key(floor,direction){return `${Number(floor)}:${direction}`;}
  score(unit,floor,direction){const e=unit.controller,distance=Math.abs(e.position-floor),busy=e.target!==null||e.calls.queue.length>0,travel=e.direction;if(!busy)return distance;const sameWay=travel!==0&&Math.sign(floor-e.position)===travel&&(direction==='up'?1:-1)===travel;return distance+(sameWay?1.5:8)+e.calls.queue.length*2;}
  isAssignmentActive(floor,direction,id=this.assignedTo(floor,direction)){const unit=id&&this.bank.get(id);if(!unit)return false;const e=unit.controller,queued=e.target===Number(floor)||e.calls.queue.some(x=>x.floor===Number(floor)&&x.direction===direction),responding=e.state==='SAME_FLOOR_RESPONSE'&&Math.round(e.position)===Number(floor),arriving=e.arrivalFloor===Number(floor)&&performance.now()<e.arrivalFlashUntil;return queued||responding||arriving;}
  hasActiveCall(floor,direction){return this.isAssignmentActive(floor,direction);}
  isUnitCallActive(id,floor,direction){const unit=this.bank.get(id);if(!unit)return false;const e=unit.controller;return e.target===Number(floor)||e.calls.queue.some(x=>x.floor===Number(floor)&&x.direction===direction)||(e.state==='SAME_FLOOR_RESPONSE'&&Math.round(e.position)===Number(floor))||(e.arrivalFloor===Number(floor)&&performance.now()<e.arrivalFlashUntil);}
  assignTo(id,floor,direction){const unit=this.bank.get(id);if(!unit||unit.calls.floorService?.isServed(Number(floor))===false)return null;this.assignments.set(this.key(floor,direction),id);if(!this.isUnitCallActive(id,floor,direction))unit.controller.request(floor,direction);return id;}
  assign(floor,direction,{excludeIds=[],requiredFloor=null}={}){const key=this.key(floor,direction),excluded=new Set(excludeIds),canServe=unit=>unit.calls.floorService?.isServed(Number(floor))!==false&&(requiredFloor===null||unit.calls.floorService?.isServed(Number(requiredFloor))!==false),current=this.assignments.get(key),currentUnit=current&&this.bank.get(current);if(currentUnit&&!excluded.has(current)&&canServe(currentUnit)&&this.isAssignmentActive(floor,direction,current))return current;const serving=[...this.bank.units.values()].filter(canServe),available=serving.filter(unit=>!excluded.has(unit.id)),candidates=available.length?available:serving;if(!candidates.length)return null;const unit=candidates.sort((a,b)=>this.score(a,floor,direction)-this.score(b,floor,direction))[0];this.assignments.set(key,unit.id);unit.controller.request(floor,direction);return unit.id;}
  assignedTo(floor,direction){return this.assignments.get(this.key(floor,direction))||null;}
}
