import { ControlPanelLayout } from '../elevator/ControlPanelLayout.js';

export class UIController {
  constructor(app){this.app=app;const settingsButton=this.el('panelToggle'),viewport=this.el('viewport');if(settingsButton&&viewport)viewport.append(settingsButton);this.bind();this.buildDynamicFloors();this.buildDesignControls();this.updateDesignValues();this.setPreview(localStorage.getItem('elevator-preview-mode')||'auto');}
  el(id){return document.getElementById(id);}
  bind(){
    const buildings=this.el('buildingPresets');if(buildings)buildings.onclick=e=>{const button=e.target.closest('[data-building]');if(!button)return;if(this.app.inside||!this.app.bank.isIdle()){this.app.log('建物テンプレートは、かごの外で全号機待機中に変更できます');return;}this.app.config.applyBuildingPreset(button.dataset.building);this.updateDesignValues();this.app.scheduleDesignUpdate('building');this.app.log(`${button.textContent.trim()}テンプレートを適用`);};
    this.el('panelToggle').onclick=()=>this.setPanel(!document.body.classList.contains('panel-open'));this.el('panelClose').onclick=()=>this.setPanel(false);this.el('panelBackdrop').onclick=()=>this.setPanel(false);
    this.el('portraitFloorToggle').onclick=()=>this.setPortraitSheet(this.el('portraitFloorSheet').hidden);this.el('portraitFloorClose').onclick=()=>this.setPortraitSheet(false);this.el('portraitOpenBtn').onclick=()=>this.app.openDoor();this.el('portraitCloseBtn').onclick=()=>this.app.closeDoor();
    this.el('portraitHallControls').onclick=e=>{const button=e.target.closest('[data-direction]');if(button)this.app.call(button.dataset.direction,button.closest('[data-elevator]')?.dataset.elevator||null);};
    document.querySelector('.preview-grid').onclick=e=>{const b=e.target.closest('[data-preview]');if(b)this.setPreview(b.dataset.preview);};
    addEventListener('keydown',e=>{if(e.key==='Escape')this.setPanel(false);});
    this.el('callUp').onclick=()=>this.app.call('up');this.el('callDown').onclick=()=>this.app.call('down');this.el('enterBtn').onclick=()=>this.app.enter();this.el('exitBtn').onclick=()=>this.app.exit();this.el('enterQuickBtn').onclick=()=>this.app.enter();this.el('exitQuickBtn').onclick=()=>this.app.exit();this.el('openBtn').onclick=()=>this.app.openDoor();this.el('closeBtn').onclick=()=>this.app.closeDoor();this.el('jumpBtn').onclick=()=>this.app.jump(Number(this.el('floorSelect').value));this.el('resetBtn').onclick=()=>location.reload();
    this.el('resetDesign').onclick=()=>this.app.resetDesign();
    this.el('speedButtons').onclick=e=>{const b=e.target.closest('[data-speed]');if(!b)return;this.app.setSpeed(Number(b.dataset.speed));document.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('active',x===b));};
    this.el('autoOperationToggle').onclick=()=>{const enabled=!this.app.passengerConfig.enabled;this.app.automaticOperation.setEnabled(enabled);this.app.log(`自動運転を${enabled?'開始':'停止'}しました`);this.updatePassengerControls();};
    this.el('demandPattern').onchange=e=>this.app.passengerConfig.setPattern(e.target.value);
    this.el('passengerInterval').onchange=e=>this.app.passengerConfig.setInterval(e.target.value);
    this.el('maxWaiting').onchange=e=>this.app.passengerConfig.setMaxWaiting(e.target.value);
    document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>this.showTab(b.dataset.tab));
    this.el('cabinPresets').onclick=e=>{const b=e.target.closest('[data-preset]');if(!b)return;this.app.config.applyCabinPreset(b.dataset.preset);this.updateDesignValues();this.app.scheduleDesignUpdate('geometry');};
    this.el('motionPresets').onclick=e=>{const b=e.target.closest('[data-preset]');if(!b)return;this.app.config.applyMotionPreset(b.dataset.preset);this.updateDesignValues();this.app.scheduleDesignUpdate('motion');};
    this.el('quickCabinPresets').onclick=e=>{const b=e.target.closest('[data-preset]');if(!b)return;if(this.app.inside||this.app.elevator.state!=='IDLE'){this.app.log('かごサイズは、かごの外で待機中に変更できます');return;}this.app.config.applyCabinPreset(b.dataset.preset);this.updateDesignValues();this.app.scheduleDesignUpdate('geometry');};
    this.el('quickMotionPresets').onclick=e=>{const b=e.target.closest('[data-preset]');if(!b)return;if(!this.app.bank.isIdle()){this.app.log('運転速度は全号機の待機中に変更できます');return;}this.app.config.applyMotionPreset(b.dataset.preset);this.updateDesignValues();this.app.scheduleDesignUpdate('motion');};
    const zoned=this.el('zonedServicePreset');if(zoned)zoned.onclick=()=>{this.app.config.applyZonedServiceDefaults();this.updateDesignValues();this.app.scheduleDesignUpdate('building');this.app.log('低層A号機・高層B号機の初期ゾーンを適用');};
    for(const id of ['A','B']){const input=this.el(`servedFloors${id}Input`);if(!input)continue;const apply=()=>{if(this.app.config.applyUnitServiceExpression(id,input.value)){input.classList.remove('input-error');this.updateDesignValues();this.updateValidation();this.app.scheduleDesignUpdate('building');}else{input.classList.add('input-error');this.updateValidation();this.app.log(`${id}号機の停止階設定を解釈できません`);}};input.addEventListener('blur',apply);input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();input.blur();}});}
  }
  setPanel(open){document.body.classList.toggle('panel-open',open);this.el('panel').setAttribute('aria-hidden',String(!open));this.el('panelToggle').setAttribute('aria-expanded',String(open));setTimeout(()=>dispatchEvent(new Event('resize')),260);}
  setPortraitSheet(open){this.el('portraitFloorSheet').hidden=!open;this.el('portraitFloorToggle').setAttribute('aria-expanded',String(open));}
  setPreview(mode){const allowed=['auto','desktop','tablet-portrait','tablet-landscape','mobile'];if(!allowed.includes(mode))mode='auto';for(const name of allowed)document.body.classList.remove(`preview-${name}`);document.body.classList.add(`preview-${mode}`);document.querySelectorAll('[data-preview]').forEach(b=>b.classList.toggle('active',b.dataset.preview===mode));localStorage.setItem('elevator-preview-mode',mode);setTimeout(()=>dispatchEvent(new Event('resize')),40);}
  showTab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));this.el('operateTab').hidden=name!=='operate';this.el('designTab').hidden=name!=='design';}
  buildDynamicFloors(){
    const select=this.el('floorSelect'),grid=this.el('floorButtons'),portraitGrid=this.el('portraitFloorButtons');select.innerHTML='';grid.innerHTML='';portraitGrid.innerHTML='';
    for(let f=1;f<=this.app.config.floors;f++){const o=document.createElement('option');o.value=f;o.textContent=`${f}F${this.app.config.isServed(f)?'':'（全号機通過）'}`;select.appendChild(o);}
    const activeId=this.app.bank?.activeId||'A',served=this.app.config.servedFloorsFor(activeId).slice().reverse(),layout=ControlPanelLayout.forCount(served.length),cols=layout.columns,density=layout.density;grid.style.gridTemplateColumns=`repeat(${cols},1fr)`;portraitGrid.style.gridTemplateColumns=`repeat(${cols},1fr)`;grid.dataset.density=density;portraitGrid.dataset.density=density;
    for(const f of served){const b=document.createElement('button');b.textContent=f;b.dataset.floor=f;b.onclick=()=>this.app.selectFloor(f);grid.appendChild(b);const mobileButton=b.cloneNode(true);mobileButton.onclick=()=>{this.app.selectFloor(f);this.setPortraitSheet(false);};portraitGrid.appendChild(mobileButton);}
    for(const id of ['A','B']){const input=this.el(`servedFloors${id}Input`);if(input)input.value=this.app.config.unitFloorServices[id].expression;}
  }
  buildDesignControls(){document.querySelectorAll('[data-key]').forEach(row=>{const key=row.dataset.key;const change=d=>{this.app.config.adjust(key,d);this.updateDesignValues();const kind=['maxSpeed','acceleration','deceleration','accelJerk','decelJerk','landingSpeed','landingDistance'].includes(key)?'motion':['floors','floorHeight'].includes(key)?'building':'geometry';this.app.scheduleDesignUpdate(kind);};row.querySelector('[data-minus]').onclick=()=>change(-1);row.querySelector('[data-plus]').onclick=()=>change(1);});}
  format(key,v){if(key==='floors')return `${v}階`;if(['maxSpeed'].includes(key))return `${v.toFixed(2)} m/s`;if(['acceleration','deceleration'].includes(key))return `${v.toFixed(2)} m/s²`;if(['accelJerk','decelJerk'].includes(key))return `${v.toFixed(2)} m/s³`;if(key==='landingSpeed')return `${v.toFixed(3)} m/s`;if(key==='landingDistance')return `${v.toFixed(2)} m`;return `${v.toFixed(2)} m`;}
  updateDesignValues(){
    const c=this.app.config;document.querySelectorAll('[data-key]').forEach(row=>{const key=row.dataset.key;row.querySelector('[data-value]').textContent=this.format(key,c[key]);});
    document.querySelectorAll('#buildingPresets [data-building]').forEach(b=>b.classList.toggle('active',b.dataset.building===c.buildingPreset));
    for(const id of ['A','B']){const input=this.el(`servedFloors${id}Input`);if(input)input.value=c.unitFloorServices[id].expression;}
    document.querySelectorAll('#cabinPresets [data-preset],#quickCabinPresets [data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===c.cabinPreset));document.querySelectorAll('#motionPresets [data-preset],#quickMotionPresets [data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===c.motionPreset));
  }
  updateValidation(){const r=this.app.config.validate(),el=this.el('validation'),serviceError=['A','B'].map(id=>this.app.config.unitFloorServices[id].lastError&&`${id}号機: ${this.app.config.unitFloorServices[id].lastError}`).filter(Boolean).join(' / ');el.className='validation';if(serviceError){el.classList.add('error');el.textContent='⚠ 停止階設定: '+serviceError;}else if(!r.ok){el.classList.add('error');el.textContent='⚠ '+r.errors.join(' / ');}else if(r.warnings.length){el.classList.add('warn');el.textContent='△ '+r.warnings.join(' / ');}else el.textContent='設定値は正常です。';}
  updatePerformance(){const el=this.el('perfText');if(el)el.textContent=`${this.app.displayFps || 0} fps / 目標30`; }
  updatePassengerControls(){const button=this.el('autoOperationToggle'),enabled=this.app.passengerConfig.enabled,stats=this.app.passengers?.stats||{waiting:0,riding:0,cars:{}};button.textContent=`自動運転：${enabled?'ON':'OFF'}`;button.classList.toggle('active',enabled);button.setAttribute('aria-pressed',String(enabled));const cars=Object.entries(stats.cars||{}).map(([id,s])=>`${id}号機 ${s.count}/${s.capacity}人${s.full?'（満員）':''}`).join('・');this.el('passengerStatus').textContent=`待機 ${stats.waiting}人・乗車 ${stats.riding}人${cars?`・${cars}`:''}`;}
  update(){
    const a=this.app,e=a.elevator,rounded=Math.round(e.position),inside=a.inside,c=a.config;this.updatePassengerControls();
    this.el('playerFloor').textContent=inside?`${rounded}F（かご内）`:`${a.playerFloor}F`;this.el('carFloor').textContent=`${e.position.toFixed(2)}F`;
    const labels={IDLE:'待機',ACCELERATING:'加速中',CRUISING:'定速運転',DECELERATING:'滑らかに減速中',LANDING:'着床進入中',ARRIVAL_WAIT:'停止・戸開待ち',DOOR:e.doors.isOpen()?'ドア全開':e.doors.target?'ドア開動作中':'ドア閉動作中'};this.el('stateText').textContent=labels[e.state]||e.state;
    this.el('queueText').textContent=[e.target,...a.calls.queue.map(x=>x.floor)].filter(x=>x!=null).join(', ')||'なし';this.el('specText').textContent=`${c.capacity}人・${c.motionPresets[c.motionPreset]?.label||'カスタム'}・${c.floors}階／${a.bank.activeId}号機 ${c.servedFloorsFor(a.bank.activeId).length}停止`;
    const aFloor=a.bank?.get('A')?.controller.position,bFloor=a.bank?.get('B')?.controller.position,activeId=a.bank?.activeId||'A',hallFocus=a.camera?.mode==='hall'?a.camera.hallFocus:null;this.el('viewLabel').textContent=inside?`${rounded}F ${activeId}号機 かご内視点`:hallFocus?`${a.playerFloor}F ${hallFocus}号機アップ`:`${a.playerFloor}F 2台ホール視点`;this.el('carLabel').textContent=hallFocus?'案内板を再タップで全体表示':`A ${aFloor?.toFixed(2)??'-'}F / B ${bFloor?.toFixed(2)??'-'}F ×${a.clock.scale}`;this.el('indicator').textContent=`${activeId} ${rounded}F ${e.direction>0?'▲':e.direction<0?'▼':'■'}`;
    this.el('hallControls').hidden=inside;this.el('cabinControls').hidden=!inside;const canEnter=a.canEnter(),enter=this.el('enterBtn'),canExit=inside&&e.doors.isBoardable();enter.disabled=!canEnter;enter.textContent=canEnter?'かごに乗る（乗車可能）':e.state==='ARRIVAL_WAIT'?'停止しました・ドア待ち':e.doors.target===1?'ドアが開いています…':'かごに乗る';const quickEnter=this.el('enterQuickBtn'),quickExit=this.el('exitQuickBtn');quickEnter.hidden=inside;quickEnter.disabled=!canEnter;quickEnter.textContent=canEnter?'かごに乗る':'到着・ドア開を待っています';quickExit.hidden=!inside;quickExit.disabled=!canExit;quickExit.textContent=canExit?'この階で降りる':'停車・ドア開を待っています';this.el('exitBtn').disabled=!canExit;const servedHere=c.isServed(a.playerFloor);this.el('callUp').disabled=!servedHere||a.playerFloor===c.floors;this.el('callDown').disabled=!servedHere||a.playerFloor===1;const hallTitle=this.el('hallServiceStatus');if(hallTitle)hallTitle.textContent=servedHere?'停止階・呼出可能':'通過階（呼出不可）';
    const portrait=this.el('portraitCabinControls'),portraitHall=this.el('portraitHallControls');portrait.hidden=!inside;portraitHall.hidden=inside;portraitHall.querySelectorAll('[data-direction]').forEach(button=>{const id=button.closest('[data-elevator]').dataset.elevator,direction=button.dataset.direction,unit=a.bank.get(id),zoned=c.hasDistinctServiceZones(),assignedId=a.dispatch.assignedTo(a.playerFloor,direction),active=zoned?a.dispatch.isUnitCallActive(id,a.playerFloor,direction):a.dispatch.isAssignmentActive(a.playerFloor,direction,assignedId),arriving=active&&unit.controller.arrivalFloor===a.playerFloor&&performance.now()<unit.controller.arrivalFlashUntil&&unit.controller.arrivalDirection===(direction==='up'?1:-1);button.disabled=!c.isServed(a.playerFloor,id)||(direction==='up'?a.playerFloor===c.floors:a.playerFloor===1);button.classList.toggle('active',active);button.classList.toggle('arriving',arriving);});if(!inside&&!this.el('portraitFloorSheet').hidden)this.setPortraitSheet(false);document.querySelectorAll('#floorButtons button,#portraitFloorButtons button').forEach(b=>{const f=Number(b.dataset.floor);b.classList.toggle('active',e.target===f||a.calls.queue.some(x=>x.floor===f));});
  }
}
