import * as THREE from 'three';

// 歩行を運行ロジックから独立させ、どの停止階でも同じ区画データを使う。
export class WalkController {
  constructor({app,viewport}){this.app=app;this.viewport=viewport;this.active=false;this.floor=1;this.position=new THREE.Vector3();this.yaw=0;this.pitch=0;this.keys=new Set();this.move=new THREE.Vector2();this.openRooms=new Set();this.createUI();this.bind();}
  createUI(){
    const style=document.createElement('style');style.textContent='.walk-ui{position:absolute;inset:0;pointer-events:none;z-index:30}.walk-toggle,.walk-exit,.walk-interact{pointer-events:auto;position:absolute;border:1px solid #76b9df;border-radius:10px;background:#09263ad9;color:#eaf8ff;font:700 14px sans-serif;padding:9px 12px}.walk-toggle{right:14px;bottom:14px}.walk-exit{left:14px;top:108px}.walk-interact{right:18px;bottom:28px;min-width:92px}.walk-stick{pointer-events:auto;position:absolute;left:18px;bottom:26px;width:104px;height:104px;border:1px solid #74bde4a8;border-radius:50%;background:#0921309c;touch-action:none}.walk-knob{position:absolute;width:42px;height:42px;border-radius:50%;left:31px;top:31px;background:#74bde4aa}.walk-hint{position:absolute;left:50%;bottom:144px;transform:translateX(-50%);padding:7px 11px;border-radius:8px;background:#06131ec9;color:#e8f5ff;font:600 13px sans-serif;white-space:nowrap}.walk-mode .quick-actions,.walk-mode #portraitHallControls,.walk-mode #portraitCabinControls,.walk-mode #panelToggle,.walk-mode .perf{display:none!important}body.preview-mobile .walk-toggle,body.preview-tablet-portrait .walk-toggle{top:166px!important;right:10px!important;bottom:auto!important}body.preview-mobile .walk-exit,body.preview-tablet-portrait .walk-exit{top:102px!important;left:10px!important}@media(max-width:599px),(max-width:900px) and (orientation:portrait){.walk-exit{top:102px!important;left:10px}.walk-interact{right:12px;bottom:18px;padding:8px 10px}.walk-stick{left:12px;bottom:18px;width:96px;height:96px}.walk-knob{left:27px;top:27px}.walk-hint{bottom:126px;max-width:calc(100% - 30px);overflow:hidden;text-overflow:ellipsis;font-size:12px}.walk-toggle{top:166px!important;right:10px!important;bottom:auto!important}}';document.head.append(style);this.style=style;
    const ui=document.createElement('div');ui.className='walk-ui';ui.innerHTML='<button class="walk-toggle" type="button">徒歩で見る</button><button class="walk-exit" type="button" hidden>徒歩を終了</button><button class="walk-interact" type="button" hidden>操作</button><div class="walk-stick" hidden><div class="walk-knob"></div></div><div class="walk-hint" hidden></div>';this.viewport.append(ui);this.ui=ui;this.toggle=ui.querySelector('.walk-toggle');this.exitButton=ui.querySelector('.walk-exit');this.interactButton=ui.querySelector('.walk-interact');this.stick=ui.querySelector('.walk-stick');this.knob=ui.querySelector('.walk-knob');this.hint=ui.querySelector('.walk-hint');this.toggle.onclick=()=>this.activate();this.exitButton.onclick=()=>this.deactivate();this.interactButton.onclick=()=>this.interact();
  }
  bind(){
    this.keydown=e=>{if(!this.active||this.editing(e.target))return;if(['w','a','s','d'].includes(e.key.toLowerCase())){this.keys.add(e.key.toLowerCase());e.preventDefault();}if(e.key.toLowerCase()==='e'){this.interact();e.preventDefault();}if(e.key==='Escape')this.deactivate();};this.keyup=e=>this.keys.delete(e.key.toLowerCase());document.addEventListener('keydown',this.keydown);document.addEventListener('keyup',this.keyup);
    this.lookMove=e=>{if(!this.active||e.pointerId!==this.lookPointerId)return;const dx=e.movementX||e.clientX-this.lookX,dy=e.movementY||e.clientY-this.lookY;this.yaw+=dx*.0032;this.pitch=THREE.MathUtils.clamp(this.pitch-dy*.0022,-.42,.28);this.lookX=e.clientX;this.lookY=e.clientY;};this.lookStop=e=>{if(e.pointerId===this.lookPointerId)this.lookPointerId=null;};this.viewport.addEventListener('pointermove',this.lookMove);document.addEventListener('pointerup',this.lookStop);document.addEventListener('pointercancel',this.lookStop);
    const moveTouch=e=>{const touch=e.touches?.[0]||e,r=this.stick.getBoundingClientRect(),dx=(touch.clientX-(r.left+r.width/2))/(r.width/2),dy=(touch.clientY-(r.top+r.height/2))/(r.height/2);this.move.set(dx,dy).clampLength(0,1);this.knob.style.transform=`translate(${this.move.x*31}px,${this.move.y*31}px)`;e.preventDefault?.();},stopTouch=()=>{this.move.set(0,0);this.knob.style.transform='';};this.stick.addEventListener('touchstart',moveTouch,{passive:false});this.stick.addEventListener('touchmove',moveTouch,{passive:false});this.stick.addEventListener('touchend',stopTouch);this.stick.addEventListener('pointerdown',e=>{this.stick.setPointerCapture?.(e.pointerId);moveTouch(e);});this.stick.addEventListener('pointermove',e=>{if(e.buttons)moveTouch(e);});this.stick.addEventListener('pointerup',stopTouch);this.stick.addEventListener('pointercancel',stopTouch);
  }
  editing(target){return ['INPUT','TEXTAREA','SELECT','BUTTON'].includes(target?.tagName);}
  get layout(){return this.app.building.floorGroups[this.floor]?.userData.floorLayout;}
  activate(){if(this.app.inside){this.app.log('かごを降りてから徒歩モードを開始してください');return;}this.floor=this.app.playerFloor;const spawn=this.layout?.spawn||{x:0,z:5.8};this.position.set(spawn.x,0,spawn.z);this.yaw=0;this.active=true;this.app.camera.setWalk(this);this.uiState();this.app.log(`${this.floor}F 徒歩モード：WASD＋マウス / スマホは左スティック。E または「操作」でドア・EVを操作`);}
  deactivate(){if(!this.active)return;this.active=false;this.keys.clear();this.move.set(0,0);if(document.pointerLockElement===this.viewport)document.exitPointerLock?.();this.app.camera.setHall(this.app.playerFloor);this.uiState();}
  dispose(){this.deactivate();document.removeEventListener('keydown',this.keydown);document.removeEventListener('keyup',this.keyup);document.removeEventListener('pointerup',this.lookStop);document.removeEventListener('pointercancel',this.lookStop);this.style.remove();this.ui.remove();}
  handleViewportPointer(event){if(!this.active||this.editing(event.target)||event.target.closest?.('.walk-ui'))return;this.lookPointerId=event.pointerId;this.lookX=event.clientX;this.lookY=event.clientY;}
  uiState(){const active=this.active;document.body.classList.toggle('walk-mode',active);this.toggle.hidden=active;this.exitButton.hidden=!active;this.interactButton.hidden=!active;this.stick.hidden=!active;this.hint.hidden=!active;}
  allowed(x,z){const layout=this.layout;if(!layout)return true;const inBound=b=>x>=b.minX&&x<=b.maxX&&z>=b.minZ&&z<=b.maxZ;const zone=layout.walkable.find(area=>inBound(area.bounds));if(!zone)return false;if((zone.id==='left-room'||zone.id==='right-room')&&!this.openRooms.has(`${this.floor}:${zone.id}`))return false;return !layout.blockers.some(blocker=>inBound(blocker.bounds));}
  moveBy(dx,dz){const radius=.19;const x=this.position.x+dx,z=this.position.z+dz;if(this.allowed(x+Math.sign(dx)*radius,this.position.z)&&this.allowed(x-Math.sign(dx)*radius,this.position.z))this.position.x=x;if(this.allowed(this.position.x,z+Math.sign(dz)*radius)&&this.allowed(this.position.x,z-Math.sign(dz)*radius))this.position.z=z;}
  nearestPortal(){const portals=this.layout?.portals||[];let best=null;for(const p of portals){const d=Math.hypot(this.position.x-p.x,this.position.z-p.z);if(d<.95&&(!best||d<best.distance))best={...p,distance:d};}return best;}
  update(dt){if(!this.active)return;let forward=(this.keys.has('w')?1:0)-(this.keys.has('s')?1:0)-this.move.y,right=(this.keys.has('d')?1:0)-(this.keys.has('a')?1:0)+this.move.x;if(forward||right){const length=Math.hypot(forward,right);forward/=length;right/=length;const speed=2.05*dt,fx=Math.sin(this.yaw),fz=-Math.cos(this.yaw),rx=-fz,rz=fx;this.moveBy((fx*forward+rx*right)*speed,(fz*forward+rz*right)*speed);}const near=this.nearestPortal(),previewTouch=document.body.classList.contains('preview-mobile')||document.body.classList.contains('preview-tablet-portrait'),touchLayout=previewTouch||matchMedia('(hover: none), (max-width: 900px) and (orientation: portrait)').matches;this.hint.hidden=touchLayout&&!near;this.hint.textContent=near?(near.kind==='elevator'?`${near.target}号機前：呼び出し / 乗車`:`${near.target==='left-room'?'01':'02'}室：${this.openRooms.has(`${this.floor}:${near.target}`)?'開いています':'Eで開く'}`):'WASDで移動';this.interactButton.textContent=near?(near.kind==='elevator'?`${near.target}を操作`:'ドアを操作'):'周囲を確認';this.app.sceneManager.needsRender=true;}
  interact(){const portal=this.nearestPortal();if(!portal){this.app.log('操作できる対象の近くまで移動してください');return;}if(portal.kind==='door'){const room=portal.target,open=!this.openRooms.has(`${this.floor}:${room}`);open?this.openRooms.add(`${this.floor}:${room}`):this.openRooms.delete(`${this.floor}:${room}`);this.app.building.setInteriorDoorOpen(this.floor,room,open);this.app.log(`${room==='left-room'?'01':'02'}室のドアを${open?'開けました':'閉じました'}`);return;}const direction=this.floor===1?'up':this.floor===this.app.config.floors?'down':'down';this.app.call(direction,portal.target);}
  canBoard(id){if(!this.active)return true;return this.nearestPortal()?.target===id;}
}
