class MotorSoundSynth {
  constructor(){this.c={masterGain:.115,motor:{baseFrequency:74,frequencyRange:51,speedExponent:.9,attack:.18,release:.55,harmonics:[{type:'sine',ratio:1,gain:1}]},inverter:{enabled:true,baseFrequency:95,frequencyRange:520,gain:.008},mechanical:{frequency:31,gain:.15},ambience:{noiseGain:.1,lowpass:850},direction:{upPitch:1.035,downPitch:.965},speedClasses:{low:{gainScale:.72,pitchScale:.86},medium:{gainScale:.86,pitchScale:.94},high:{gainScale:1.08,pitchScale:1.06},ultra:{gainScale:1.18,pitchScale:1.12}}};this.context=null;this.master=null;this.oscillators=[];this.lastDirection=1;}
  ensure(){const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return null;if(!this.context)this.context=new Ctx();if(this.context.state==='suspended')this.context.resume();if(!this.master)this.build();return this.context;}
  build(){const c=this.c,ctx=this.context;this.master=ctx.createGain();this.master.gain.value=0;this.master.connect(ctx.destination);for(const h of c.motor.harmonics){const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=h.type;gain.gain.value=h.gain;osc.connect(gain).connect(this.master);osc.start();this.oscillators.push({osc,h});}if(c.inverter.enabled){this.inverter=ctx.createOscillator();this.inverter.type='sawtooth';const gain=ctx.createGain();gain.gain.value=c.inverter.gain;this.inverter.connect(gain).connect(this.master);this.inverter.start();}this.mechanical=ctx.createOscillator();this.mechanical.type='triangle';const mechanicalGain=ctx.createGain();mechanicalGain.gain.value=c.mechanical.gain;this.mechanical.connect(mechanicalGain).connect(this.master);this.mechanical.start();const buffer=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;this.noise=ctx.createBufferSource();this.noise.buffer=buffer;this.noise.loop=true;const filter=ctx.createBiquadFilter(),noiseGain=ctx.createGain();filter.type='lowpass';filter.frequency.value=c.ambience.lowpass;noiseGain.gain.value=c.ambience.noiseGain;this.noise.connect(filter).connect(noiseGain).connect(this.master);this.noise.start();}
  unlock(){this.ensure();}
  update(velocity,acceleration,direction,motionPreset,maxSpeed,audible){if(!this.master)return;const c=this.c,now=this.context.currentTime,absoluteSpeed=Math.abs(velocity);if(direction)this.lastDirection=Math.sign(direction);const normalized=Math.max(0,Math.min(1,absoluteSpeed/Math.max(.1,maxSpeed||1))),tuning=c.speedClasses[motionPreset]||c.speedClasses.medium,pitch=(this.lastDirection>=0?c.direction.upPitch:c.direction.downPitch)*tuning.pitchScale,frequency=(c.motor.baseFrequency+c.motor.frequencyRange*normalized**c.motor.speedExponent)*pitch;for(const {osc,h} of this.oscillators)osc.frequency.setTargetAtTime(frequency*h.ratio,now,.030);if(this.inverter)this.inverter.frequency.setTargetAtTime((c.inverter.baseFrequency+c.inverter.frequencyRange*(.18+.82*normalized))*pitch,now,.025);this.mechanical.frequency.setTargetAtTime(c.mechanical.frequency*tuning.pitchScale*(1+normalized*.16),now,.045);const speedEnvelope=Math.pow(normalized,.8),accelBody=1+Math.min(.10,Math.abs(acceleration)*.07),level=audible?c.masterGain*tuning.gainScale*speedEnvelope*accelBody:0,timeConstant=!audible?.025:absoluteSpeed<.003?.10:acceleration>=0?.055:.075;this.master.gain.setTargetAtTime(level,now,timeConstant);}
}
class AudioManager {
  constructor(){this.config=new ElevatorSoundConfig();this.synth=new ToneSynth(this.config);this.motor=new MotorSoundSynth();}
  unlock(){this.synth.unlock();this.motor.unlock();}
  playCall(){this.synth.playCall();}
  playArrival(direction){if(direction!==0)this.synth.playArrival(direction);}
  updateMotor(velocity,acceleration,direction,motionPreset,maxSpeed,audible){this.motor.update(velocity,acceleration,direction,motionPreset,maxSpeed,audible);}
}
