export class PassengerManager {
  constructor({bank,building,dispatch,config,renderer,log}){this.bank=bank;this.building=building;this.dispatch=dispatch;this.config=config;this.renderer=renderer;this.log=log;this.passengers=[];this.nextId=1;this.occupancy=new Map([...bank.units.keys()].map(id=>[id,0]));}
  waitingAt(floor){return this.passengers.filter(p=>p.origin===floor&&(p.state==='waiting'||p.state==='boarding')).length;}
  chooseTrip(pattern){const floors=this.building.floorService.servedNumbers;if(floors.length<2)return null;let origin,destination;const pick=items=>items[Math.floor(Math.random()*items.length)];if(pattern==='morning'&&Math.random()<.75){origin=floors[0];destination=pick(floors.slice(1));}else if(pattern==='evening'&&Math.random()<.75){origin=pick(floors.slice(1));destination=floors[0];}else{origin=pick(floors);destination=pick(floors.filter(f=>f!==origin));}return {origin,destination};}
  spawn(pattern){const trip=this.chooseTrip(pattern);if(!trip||this.waitingAt(trip.origin)>=this.config.maxWaitingPerFloor)return false;const direction=trip.destination>trip.origin?'up':'down',assignedId=this.dispatch.assign(trip.origin,direction),passenger={id:this.nextId++,...trip,direction,assignedId,state:'waiting',elapsed:0};this.passengers.push(passenger);this.renderer.create(passenger,this.building.getShaftCenter(assignedId));this.log(`乗客${passenger.id}：${trip.origin}F→${trip.destination}F（${assignedId}号機待ち）`);return true;}
  update(dt){for(const unit of this.bank.units.values())unit.doors.setObstructed(false);for(const p of this.passengers)if(p.state==='boarding'||p.state==='exiting')this.bank.get(p.assignedId)?.doors.setObstructed(true);for(const p of [...this.passengers]){const unit=this.bank.get(p.assignedId);if(!unit)continue;if(p.state==='waiting'){const count=this.occupancy.get(unit.id)||0;if(count<this.config.capacity&&Math.abs(unit.controller.position-p.origin)<.04&&unit.doors.isBoardable()){p.state='boarding';p.elapsed=0;this.occupancy.set(unit.id,count+1);unit.controller.extendDoorHold(2.2);this.renderer.beginBoarding(p,unit);}else if(count>=this.config.capacity){p.elapsed=(p.elapsed||0)+dt;if(p.elapsed>=2){unit.calls.cancel(p.origin,p.direction);p.assignedId=this.dispatch.assign(p.origin,p.direction,{excludeIds:[unit.id]});p.elapsed=0;this.renderer.reassignWaiting(p,this.bank.get(p.assignedId));this.log(`乗客${p.id}：${unit.id}号機満員のため${p.assignedId}号機を待ちます`);}}}else if(p.state==='boarding'){p.elapsed+=dt;this.renderer.updateTransition(p,Math.min(1,p.elapsed/1.25));if(p.elapsed>=1.25){p.state='riding';p.elapsed=0;this.renderer.board(p,unit,(this.occupancy.get(unit.id)||1)-1);unit.controller.request(p.destination,'car',{closeDoors:false});unit.controller.extendDoorHold(1.5);this.log(`乗客${p.id}：${unit.id}号機へ乗車・${p.destination}Fを登録`);}}else if(p.state==='riding'&&Math.abs(unit.controller.position-p.destination)<.04&&unit.doors.isBoardable()){p.state='exiting';p.elapsed=0;this.occupancy.set(unit.id,Math.max(0,(this.occupancy.get(unit.id)||1)-1));unit.controller.extendDoorHold(1.8);this.renderer.beginExit(p,unit);}else if(p.state==='exiting'){p.elapsed+=dt;this.renderer.updateTransition(p,Math.min(1,p.elapsed/1.35));if(p.elapsed>=1.35){this.renderer.remove(p);this.passengers.splice(this.passengers.indexOf(p),1);this.log(`乗客${p.id}：${p.destination}Fで降車`);}}}}
  get stats(){return {waiting:this.passengers.filter(p=>p.state==='waiting'||p.state==='boarding').length,riding:this.passengers.filter(p=>p.state==='riding'||p.state==='exiting').length,total:this.passengers.length};}
  dispose(){this.renderer.dispose();this.passengers=[];this.occupancy.clear();}
}
